# Generated by Django 3.2.9 on 2021-11-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='qq',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
